# These settings were set by the catalyst build script that automatically
# built this stage.
# Please consult /usr/share/portage/config/make.conf.example for a more
# detailed example.
COMMON_FLAGS="-march=znver3 -mtune=znver3 -O3 -pipe"
CFLAGS="${COMMON_FLAGS} -flto=thin"
CXXFLAGS="${COMMON_FLAGS} -flto=thin"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"

CC="clang"
CXX="clang++"
CPP="clang-cpp"
AR="llvm-ar"
NM="llvm-nm"
RANLIB="llvm-ranlib"
LDFLAGS="-fuse-ld=lld --rtlib=compiler-rt --unwindlib=libunwind -Wl,--as-needed"
RUSTFLAGS="-C opt-level=2 -C target-cpu=native -C linker-plugin-lto -C codegen-units=1"
GOAMD64="v3"

USE="systemd zstd lm-sensors lto pgo clang llvm lld wayland wl-roots pipewire vulkan vaapi opencl gles2 opengl dbus policykit alsa udev lz4 bluetooth cups nftables -iptables -bindist -static-libs -kde -gnome -gtk2 -nls -wifi -X -x11 -openrc -zeroconf -samba -smb -telemetry -debug -handbook -semantic-desktop"
#USE="systemd lto pgo zstd lz4 lm_sensors dbus policykit udev lz4 bluetooth -bindist -wifi -X -openrc"

# VIDEO_CARDS="amdgpu radeonsi"

LLVM_TARGETS="AMDGPU X86"

#CPU_FLAGS_X86="aes avx avx2 f16c fma3 mmx mmxext pclmul popcnt rdrand sha sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 vpclmulqdq"
INPUT_DEVICES="libinput"
MAKEOPTS="-j16 -l18"
EMERGE_DEFAULT_OPTS="--jobs 5 --load-average 18 --with-bdeps=y --verbose-conflicts"

# PORTAGE_SCHEDULING_POLICY="idle" #Options are idle, batch, other 
PORTAGE_NICENESS="15"
# PORTAGE_IONICE_COMMAND="ionice -c 2 -n 0 -p \${PID}"
PORTAGE_IONICE_COMMAND="ionice -c 2 -n 7 -p \${PID}"

PORTAGE_TMPDIR="/var/tmp/portage"

ACCEPT_KEYWORDS="~amd64"
ACCEPT_LICENSE="*"
FEATURES="parallel-fetch parallel-install candy"
L10N="en en-US he"

# This sets the language of build output to English.
# Please keep this setting intact when reporting bugs.
LC_MESSAGES=C.UTF-8
