splash = false

wallpaper {
    monitor = HDMI-A-1
    path = /home/kixadmin/Pictures/Wallpapers/pexels-jplenio-3131634.jpg
}

wallpaper {
    monitor = HDMI-A-2
    path = /home/kixadmin/Pictures/Wallpapers/pexels-jplenio-3131634.jpg
}

wallpaper {
    monitor = DP-1
    path = /home/kixadmin/Pictures/Wallpapers/pexels-eberhardgross-443446.jpg
}
