h seek -5
l seek 5
H seek -60
L seek 60
0 seek 0 absolute
k add volume 5
j add volume -5
m cycle mute
SPACE cycle pause
[ multiply speed 0.9091
] multiply speed 1.1
BS set speed 1.0
a cycle-values video-aspect-override 2.35:1 -1
w add panscan -0.1
e add panscan +0.1
Alt+k add video-pan-y 0.1
Alt+j add video-pan-y -0.1
Alt+h add video-pan-x 0.1
Alt+l add video-pan-x -0.1
s cycle sub
Alt+s cycle sub-visibility
x screenshot
X screenshot video
q quit
ESC set fullscreen no
