---
- name: Set Portage profile
  command: eselect profile set default/linux/amd64/23.0/no-multilib/systemd
  become: true
  check_mode: false
  changed_when: false

- name: Clone powerhouse-repo overlay
  ansible.builtin.git:
    repo: git@github.com:kixago/powerhouse-repo.git
    dest: /var/db/repos/powerhouse-repo
    version: main
  become: true
  when: not ansible_check_mode

- name: Stow portage config
  ansible.builtin.shell: |
    stow -d {{ stow_dir }} -t / portage
  become: true
  check_mode: false
  register: stow_portage
  changed_when: stow_portage.rc != 0
