# created by eselect-repo

[hyproverlay]
location = /var/db/repos/hyproverlay
sync-type = git
sync-uri = https://codeberg.org/hyproverlay/hyproverlay.git

[another-brave-overlay]
location = /var/db/repos/another-brave-overlay
sync-type = git
sync-uri = https://github.com/falbrechtskirchinger/another-brave-overlay.git

[guru]
location = /var/db/repos/guru
sync-type = git
sync-uri = https://github.com/gentoo-mirror/guru.git
